### ISSUE TITLE
Make _comment node visible for syntax highlighting

### ISSUE THREAD

**Issue by theHamsta** [latex-lsp/tree-sitter-latex#1]
https://github.com/nvim-treesitter/nvim-treesitter allows to use tree-sitter parser to enable syntax highlighting in Neovim. We would like to create some highlight queries to support highlighting for tree-sitter-latex. First, thank you for creating this robust and hierarchical grammar for LaTex!

I encountered two minor issue when creating the highlights

 - right now comments are hidden nodes. This means we cannot capture them by `(comment)`. Which is very useful for syntax highlighting
 - the `command: (_) ;; not visible in grammar` field of section/subsection commands is not visible in the grammar as the children (`\\subsection`/`\\section``) are defined by regexes and not a dedicated rule

Ref: https://github.com/nvim-treesitter/nvim-treesitter/pull/1106

**Comment by pfoerster** [comment]
Thanks for the report. The last two commits on the master branch should fix the issue.
Please let me know if there needs anything else to be done.

**Comment by theHamsta** [comment]
Works really nice! Thank you a lot!
