### ISSUE TITLE
Text in braces in math environments is highlighted incorrectly.

### ISSUE THREAD

**Issue by gi1242** [latex-lsp/tree-sitter-latex#101]
Here's a minimal example showing the errors:

```tex
\documentclass{amsart}

\begin{document}
Text in braces in math environments is highlighted incorrectly.

For instance the \texttt{equation} or \texttt{align} environments:
\begin{equation}
  \frac{a}{b} % Arguments are in text mode, but should be math
  { c^2 } % Contents of {...} are in text mode but should be math
\end{equation}
\begin{align}
  \frac{a}{b} % Arguments are in text mode, but should be math
  a = b
  { c^2 } % Contents of {...} are in text mode but should be math
\end{align}

However, inline math works:
$
  \frac{a}{b} % Arguments are in math mode as expected.
  { c^2 } % Contents of {...} are in math mode as expected.
$

Displayed equations also work:
\[
  \frac{a}{b} % Arguments are in math mode as expected.
  { c^2 } % Contents of {...} are in math mode as expected.
\]
\end{document}
```

I'm using Neovim with tree-sitter-latex version `2ae2021d7b224fb6aa57b760e0d146059f943bb8` (latest as of the time of writing).

Please let me know if I can help trace down the issue in any way.

**Comment by gi1242** [comment]
Here's a screenshot:

![image](https://github.com/latex-lsp/tree-sitter-latex/assets/1884258/d96d1cbe-bfee-4d61-8022-1bc5b9f54a7b)

**Comment by clason** [comment]
Please show the parsed output (`:InspectTree`) rather than a screenshot (which depends on queries and colorschemes, none of which are relevant to this repo).

**Comment by gi1242** [comment]
Here's the output of `:InspectTree` on the same file:

(class_include) ; [1:1 - 22]
 path: (curly_group_path) ; [1:15 - 22]
  path: (path) ; [1:16 - 21]
(generic_environment) ; [2:1 - 27:14]
 begin: (begin) ; [2:1 - 16]
  name: (curly_group_text) ; [2:7 - 16]
   text: (text) ; [2:8 - 15]
    word: (word) ; [2:8 - 15]
 (text) ; [3:1 - 5:66]
  word: (word) ; [3:1 - 4]
  word: (word) ; [3:6 - 7]
  word: (word) ; [3:9 - 14]
  word: (word) ; [3:16 - 17]
  word: (word) ; [3:19 - 22]
  word: (word) ; [3:24 - 35]
  word: (word) ; [3:37 - 38]
  word: (word) ; [3:40 - 50]
  word: (word) ; [3:52 - 63]
  word: (word) ; [5:1 - 3]
  word: (word) ; [5:5 - 12]
  word: (word) ; [5:14 - 16]
  word: (generic_command) ; [5:18 - 34]
   command: (command_name) ; [5:18 - 24]
   arg: (curly_group) ; [5:25 - 34]
    (text) ; [5:26 - 33]
     word: (word) ; [5:26 - 33]
  word: (word) ; [5:36 - 37]
  word: (generic_command) ; [5:39 - 52]
   command: (command_name) ; [5:39 - 45]
   arg: (curly_group) ; [5:46 - 52]
    (text) ; [5:47 - 51]
     word: (word) ; [5:47 - 51]
  word: (word) ; [5:54 - 66]
 (math_environment) ; [6:1 - 9:14]
  begin: (begin) ; [6:1 - 16]
   name: (curly_group_text) ; [6:7 - 16]
    text: (text) ; [6:8 - 15]
     word: (word) ; [6:8 - 15]
  (generic_command) ; [7:3 - 8:9]
   command: (command_name) ; [7:3 - 7]
   arg: (curly_group) ; [7:8 - 10]
    (text) ; [7:9 - 9]
     word: (word) ; [7:9 - 9]
   arg: (curly_group) ; [7:11 - 13]
    (text) ; [7:12 - 12]
     word: (word) ; [7:12 - 12]
   (line_comment) ; [7:15 - 62]
   arg: (curly_group) ; [8:3 - 9]
    (text) ; [8:5 - 7]
     word: (word) ; [8:5 - 5]
     word: (superscript) ; [8:6 - 7]
      superscript: (word) ; [8:7 - 7]
  (line_comment) ; [8:11 - 65]
  end: (end) ; [9:1 - 14]
   name: (curly_group_text) ; [9:5 - 14]
    text: (text) ; [9:6 - 13]
     word: (word) ; [9:6 - 13]
 (math_environment) ; [10:1 - 14:11]
  begin: (begin) ; [10:1 - 13]
   name: (curly_group_text) ; [10:7 - 13]
    text: (text) ; [10:8 - 12]
     word: (word) ; [10:8 - 12]
  (generic_command) ; [11:3 - 13]
   command: (command_name) ; [11:3 - 7]
   arg: (curly_group) ; [11:8 - 10]
    (text) ; [11:9 - 9]
     word: (word) ; [11:9 - 9]
   arg: (curly_group) ; [11:11 - 13]
    (text) ; [11:12 - 12]
     word: (word) ; [11:12 - 12]
  (line_comment) ; [11:15 - 62]
  (text) ; [12:3 - 3]
   word: (word) ; [12:3 - 3]
  (text) ; [12:7 - 7]
   word: (word) ; [12:7 - 7]
  (curly_group) ; [13:3 - 9]
   (text) ; [13:5 - 7]
    word: (word) ; [13:5 - 5]
    word: (superscript) ; [13:6 - 7]
     superscript: (word) ; [13:7 - 7]
  (line_comment) ; [13:11 - 65]
  end: (end) ; [14:1 - 11]
   name: (curly_group_text) ; [14:5 - 11]
    text: (text) ; [14:6 - 10]
     word: (word) ; [14:6 - 10]
 (text) ; [16:1 - 7]
  word: (word) ; [16:1 - 7]
 (text) ; [16:10 - 27]
  word: (word) ; [16:10 - 15]
  word: (word) ; [16:17 - 20]
  word: (word) ; [16:22 - 27]
 (inline_formula) ; [17:1 - 20:1]
  (generic_command) ; [18:3 - 19:9]
   command: (command_name) ; [18:3 - 7]
   arg: (curly_group) ; [18:8 - 10]
    (text) ; [18:9 - 9]
     word: (word) ; [18:9 - 9]
   arg: (curly_group) ; [18:11 - 13]
    (text) ; [18:12 - 12]
     word: (word) ; [18:12 - 12]
   (line_comment) ; [18:15 - 55]
   arg: (curly_group) ; [19:3 - 9]
    (text) ; [19:5 - 7]
     word: (word) ; [19:5 - 5]
     word: (superscript) ; [19:6 - 7]
      superscript: (word) ; [19:7 - 7]
  (line_comment) ; [19:11 - 59]
 (text) ; [22:1 - 30]
  word: (word) ; [22:1 - 9]
  word: (word) ; [22:11 - 19]
  word: (word) ; [22:21 - 24]
  word: (word) ; [22:26 - 30]
 (displayed_equation) ; [23:1 - 26:2]
  (generic_command) ; [24:3 - 25:9]
   command: (command_name) ; [24:3 - 7]
   arg: (curly_group) ; [24:8 - 10]
    (text) ; [24:9 - 9]
     word: (word) ; [24:9 - 9]
   arg: (curly_group) ; [24:11 - 13]
    (text) ; [24:12 - 12]
     word: (word) ; [24:12 - 12]
   (line_comment) ; [24:15 - 55]
   arg: (curly_group) ; [25:3 - 9]
    (text) ; [25:5 - 7]
     word: (word) ; [25:5 - 5]
     word: (superscript) ; [25:6 - 7]
      superscript: (word) ; [25:7 - 7]
  (line_comment) ; [25:11 - 59]
 end: (end) ; [27:1 - 14]
  name: (curly_group_text) ; [27:5 - 14]
   text: (text) ; [27:6 - 13]
    word: (word) ; [27:6 - 13]

**Comment by clason** [comment]
Can you maybe minimize that example so one can see what's going on?

**Comment by clason** [comment]
Looks correct to me, as far as the tree is concerned.  AFAICT, `(text)` is a generic node for any non-special character; it is _not_ the same as `(text_mode)`.

Any highlight errors are query issues and belong at nvim-treesitter.

**Comment by gi1242** [comment]
OK, on a second machine (with the same configs) I see the highlighting all correct. Regardless, from the output of `InspectTree` it looks like it isn't a treesitter issue. I'll trace down the problem and open a new issue if I can reproduce it consistently.

Sorry to bother you and thanks for the quick responses.
