### ISSUE TITLE
File navigation slow in Neovim when highlight module is enabled

### ISSUE THREAD

**Issue by igrvlhlb** [latex-lsp/tree-sitter-latex#12]
I've been using [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) with the only purpose of syntax highlighting and
my experience has been good so far. However, these days I had to work on a .tex file (258 lines) and I was seeing considerable slowdown in navigation.<br>
There was no problem in scrolling down the page in chunks, such as with the `CTRL-D` command in normal mode. But if I moved the cursor untill the last line of the current page and moved it down again, the slowdown happens (specially if I kept moving it downwards).<br>
Then I began investigating. If I disabled nvim-treesitter the issue would disappear. But I found it very suspicious, as It never presented anything like that in other files. That said, I tried disabling the highlight module and everything worked fine (except that now there was only the neovim's default syntax highlighting).<br>
I tested with other .tex files and I can confirm It happened with all of them. Also, I can tell that the slowdown happed only in .tex files (also tried to reproduce the steps in other language's files I have in my machine, but they were fine).

**Comment by clason** [comment]
You should report this at https://github.com/nvim-treesitter/nvim-treesitter, since that's where neovim's (still experimental!) tree-sitter syntax highlighting is developed. If possible, add some more details (for example, a sample TeX files, and more details about your neovim version etc.) there.

**Comment by igrvlhlb** [comment]
Yes, you're right. There was no issue with the parser. Using the official release of neovim solved the problem, as recommended in [this issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/1712). So the issue wasn't with the plugin also. Thank you!
