### ISSUE TITLE
Feature request: Highlight contents inside \iffalse ... \fi as comment

### ISSUE THREAD

**Issue by ChasingZenith** [latex-lsp/tree-sitter-latex#15]
Highlighting the content inside `\iffalse ... \fi` as comment may be useful.

As suggested in this [stackoverflow article](https://tex.stackexchange.com/questions/17816/commenting-out-large-sections/17818#17818), there is two popular way to comment out a large block of contents.
A lot of information is also provided in this lervag/vimtex#1988 issue.

```latex
\iffalse
something here
\fi
```
and
```latex
\usepackage{comment} % in the preamble
\begin{comment}
 something
\end{comment}
```
### Now
![Screenshot_20211027_202349](https://user-images.githubusercontent.com/22112456/139064879-e1b0d5bf-03cf-4081-bc12-65f8bb2328ae.png)

![Screenshot_20211027_203604](https://user-images.githubusercontent.com/22112456/139066898-ce0ecc72-7812-4cfc-be10-9cfb292b331f.png)
### Expect
![Screenshot_20211027_201655](https://user-images.githubusercontent.com/22112456/139064522-6e676ad9-ce9d-4115-9b77-0c6b3104ff12.png)
This is also what `vimtex` give now.

**Comment by pfoerster** [comment]
Thanks for the suggestion. The latest grammar on the master branch now contains additional rules to match those constructs 👍 .
