### ISSUE TITLE
textcolor is not parsered wrong

### ISSUE THREAD

**Issue by dirichy** [latex-lsp/tree-sitter-latex#159]
```latex
\textcolot{red}{some text}
```
is parsered seperately, but we know {some text} is also arg of \\textcolor. 
![IMG_4829](https://github.com/user-attachments/assets/f96487bd-b830-48da-813b-ea0a718f8a41)

**Comment by dirichy** [comment]
Some times this makes werid things such as the curly group is a uncle node of the color reference node, which make me can’t write a query to find the second arg for \textcolor

**Comment by clason** [comment]
That needs to be fixed on the parser side.

**Comment by jdujava** [comment]
After 6706f88d5b563ed8aaf7babb45e5f85dab001db1 arguments of `\textcolor` should be properly recognized. Can you update grammar you use and check whether it works?

**Comment by dirichy** [comment]
Iwonder how to update it. I use nvim-treesitter and when I try to update it, it says “up to date”. Should I clone this repo and compile by my self?

**Comment by jdujava** [comment]
Try to run `:TSUpdateSync latex` (and wait a little bit).

_I am not sure about the details (please someone correct me if I am wrong), but since `latex` has `requires_generate_from_grammar = true`, sometimes it is required to run forementioned command (to update to the latest grammar). (I would think that this would be done automatically, but I vaguely remember that to get things to work I needed to run it manually)._

**Comment by dirichy** [comment]
I tried :TSUpdateSync latex and it didn’t work. Even I try to uninstall the latex parser and reinstall it, the textcolor cmd is still parsered wrong. Should I clone this repo to compile it manually?

**Comment by jdujava** [comment]
You certainly can try. Try to generate parser from grammar with `tree-sitter generate` in the repo directory with `grammar.js`, 

I tell `nvim-treesitter` to work with local repo with
```lua
local parser_config = require('nvim-treesitter.parsers').get_parser_configs()
parser_config.latex = {                                                      
    install_info = {                                                         
        url = '/path/to/repo/with/tree-sitter-latex',                 
        files = { 'src/parser.c', 'src/scanner.c' },                         
        requires_generate_from_grammar = true,                               
    },                                                                       
    filetype = 'tex',                                                        
}                                                                            
```
and then install with `:TSInstallSync` latex.

**Comment by dirichy** [comment]
Thank you, it works. 
Sorry for reply so late.
