### ISSUE TITLE
Segmentation fault with Neovim 0.6.0

### ISSUE THREAD

**Issue by yhu266** [latex-lsp/tree-sitter-latex#16]
It seems this LaTeX parser causes segmentation fault with Neovim 0.6.0. I will update with more details about reproducing this issue.

**Comment by pfoerster** [comment]
Are there any updates on this issue? Although, I am not sure that this grammar can cause a seg fault on its own (no external scanner).

**Comment by yhu266** [comment]
I'm so sorry to waste your time. It was a configuration error on my own, not on this parser. Closing.
