### ISSUE TITLE
Remove `src/parser.c` and  `src/tree_sitter/` from `.gitignore`

### ISSUE THREAD

**Issue by win0err** [latex-lsp/tree-sitter-latex#172]
Emacs function [treesit-install-language-grammar](https://github.com/emacs-mirror/emacs/blob/336e977f18f0f823af229e037f0df71505366839/lisp/treesit.el#L3678) requires `src/parser.c` to exist.

I suggest to remove these lines from `.gitignore`:
```gitignore
src/parser.c
src/tree_sitter/
```

#### Official grammars
- https://github.com/tree-sitter/tree-sitter-c/tree/master/src
- https://github.com/tree-sitter/tree-sitter-php/tree/master/php/src
- https://github.com/tree-sitter/tree-sitter-go/tree/master/src
- https://github.com/tree-sitter/tree-sitter-python/tree/master/src

#### Third-party grammars
- https://github.com/tree-sitter-grammars/tree-sitter-markdown/tree/split_parser/tree-sitter-markdown/src
- https://github.com/Wilfred/tree-sitter-elisp/tree/main/src

**Comment by clason** [comment]
No, this is deliberate; parsers are too big to track under version control; the linked parsers will also stop including them soon.

These _will_ be part of release artefacts, so if Emacs can't handle including a `tree-sitter generate` step in its install procedure, you should wait until the necessary infrastructure is set up. (Hopefully before Christmas.)

**Comment by win0err** [comment]
@clason: Thank you for your detailed answer!

**Comment by win0err** [comment]
> the linked parsers will also stop including them soon

Could you share some sources for this information? I would like to ensure that these plans are not limited to this repository. It would be helpful to have links to them so that the corresponding changes can be made in Emacs.

**Comment by clason** [comment]
https://github.com/tree-sitter/tree-sitter/issues/930 (under "Mergeable Git Repos"). The plans are definitely not limited to this repository; _all_ parsers under https://github.com/tree-sitter-grammars (that don't already) will do this.

**Comment by real-or-random** [comment]
> [tree-sitter/tree-sitter#930](https://github.com/tree-sitter/tree-sitter/issues/930) (under "Mergeable Git Repos"). The plans are definitely not limited to this repository; _all_ parsers under [@tree-sitter-grammars](https://github.com/tree-sitter-grammars) (that don't already) will do this.

Unfortunately, it appears that progress on this has stalled, and the ecosystem is split. Some repos have removed `parser.c` and some still have it.

If I may suggest some kind of pragmatic middle ground, then what `tree-sitter-perl` does seems reasonable. They have the `parser.c` in a `release` branch and AFAIU, they also have a GitHub Actions workflow to update that branch. See https://github.com/tree-sitter-perl/tree-sitter-perl/issues/142

**Comment by clason** [comment]
No, that is literally the worst of both worlds. If the parser is small enough for the convenience to outweigh the churn, commit it; otherwise don't and rely on the release workflow.
