### ISSUE TITLE
Language injection: Python

### ISSUE THREAD

**Issue by FranzAtGithub** [latex-lsp/tree-sitter-latex#18]
Hey :)

I am not even sure if this is the correct place to ask for this but in lack of a better idea I will try :)

I want to use python code inside my latex using the pythontex package (see [here](https://tex.stackexchange.com/questions/629243/create-latex-boolean-from-pythontex) for example).

Should this work out of the box?
Is it something that should be incorporated into the latex grammar?

I use tree-sitter through neovims nvim-treesitter plugin.

Ty for any help.

**Comment by pfoerster** [comment]
Thanks for the question. The language injection queries are not located inside this repository. Instead, they are part of the `nvim-treesitter` repository: https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/latex

I will push a new version of the grammar soon, which will handle verbatim content correctly (this requires an external scanner). Afterwards, the language injection queries need to be updated to account for the common locations that contain code written in other languages (lstlisting, minted, pythontex, ...).

**Comment by FranzAtGithub** [comment]
Thank you very much for your answer. I will try to sum up what I got from it.

I checked the [injections file](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/latex/injections.scm) in the `nvim-treesitter` repository. Its only line is about comments. For my use case there should be a line/section concerning python code injection.

You will update the grammar provided by this repository.
Did you plan that update independent of my issue?
Does it make sense to open an issue in `nvim-treesitter` before you updated the grammar?

**Comment by pfoerster** [comment]
> Did you plan that update independent of my issue?

Yes, there is some code on the `develop` branch: https://github.com/latex-lsp/tree-sitter-latex/tree/develop
There is one bug that needs to be fixed with the WASM target (somehow the external scanner crashes in the WASM runtime; otherwise, it works just fine). Once that issue is sorted out and the latest contributions are integrated, I will merge it into `master`. 

> Does it make sense to open an issue in nvim-treesitter before you updated the grammar?

There will be quite a lot of changes so I recommend waiting a little bit so there is no duplicate work.

**Comment by FranzAtGithub** [comment]
got it. Thank you very much!

**Comment by pfoerster** [comment]
Sorry for the long wait. The new grammar has just been merged to the master branch. If there are any issues with language injection, please open a new issue.

**Comment by FranzAtGithub** [comment]
Hey thank you very much for letting me know about the update.

Syntax highlighting for my injected python code still does not work but I didn't expect that anyway.
For what I understand there is still the need to update https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/latex/injections.scm.

I have read a minimal amount of tree-sitter documentation here
https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries
and here
https://tree-sitter.github.io/tree-sitter/creating-parsers#the-grammar-dsl

Your grammar mentions the `pycode` environment of `pythontex` explicitly in
https://github.com/latex-lsp/tree-sitter-latex/blob/c454b3207f0e5d8a6fb82bcedcaf1db07a805024/grammar.js#L474-L499
so an injection rule in the nvim-treesitter repo would need to use those definitions?

**Comment by clason** [comment]
Note that the new parser is a breaking update; it will take time to get nvim-treesitter updated to use it. (Right now it's still locked at the old version, so no surprise that it isn't working.)

**Comment by clason** [comment]
Yes. Someone has to sit down and Do The Work.

**Comment by FranzAtGithub** [comment]
@clason  Wow! I was just blown away by the fact that you are Cristian Clason ;)
I am currently reading your articles together with T. Valkonen on generalized PDPS algorithms.

I would really like to "Do The Work" but I am afraid it would take me very long as I still have very limited knowledge of tree-sitter. I would have tried to update a single injection file with a small query. but overhauling the complete queries seems to be more than I can handle atm.

Anyway, thank you once more for your answers. Really made my day to have met you at Github!

**Comment by clason** [comment]
What a small world :) I'm happy you find the articles interesting!

(I'm trying to do the work, but my knowledge of tree-sitter is quite limited as well, so it's slow going.)
