### ISSUE TITLE
Wrong parsing with half-open intervals and macros

### ISSUE THREAD

**Issue by cionx** [latex-lsp/tree-sitter-latex#2]
I use the grammar from this project via [nvim-treesitter][1]. But I ran into a problem with half-open intervals and macros, resulting in wrong syntax highlight:

![2]
<details>
<summary>Code</summary>

```latex
\documentclass{scrartcl}

\usepackage{mathtools}

\begin{document}

	Let $A \coloneqq (-\infty, 0]$ and $B \coloneqq [0, \infty)$.

\end{document}
```

</details>

According to https://github.com/nvim-treesitter/nvim-treesitter/issues/1285#issuecomment-835893578 (and the parsing result provided there) this problem stems from the current parser/grammar.

[1]: https://github.com/nvim-treesitter/nvim-treesitter
[2]: https://user-images.githubusercontent.com/7231796/117585058-af164f00-b110-11eb-8d32-8202555b6e50.png

**Comment by zacmar** [comment]
As an aside, one should probably use `\(` as inline math delimiter over `$` (and similarly `\[` over `$$` for display math), see [https://tex.stackexchange.com/questions/510/are-and-preferable-to-dollar-signs-for-math-mode](https://tex.stackexchange.com/questions/510/are-and-preferable-to-dollar-signs-for-math-mode). Parsing something where the "begin-delimiter" and "end-delimiter" are the same is a nightmare. Even worse if there exists another set of identical delimiters, that are the same, just doubled (consider `$ a + b $$ b + c$`). Interestingly, the parse tree almost looks worse in this case (I don't see inline_formula anywhere, but some errors):

```latex
\documentclass{scrartcl}

\usepackage{mathtools}

\begin{document}

	Let \( A \coloneqq (-\infty, 0] \) and \( B \coloneqq [0, \infty) \).

\end{document}
```


```
comment [0, 0] - [0, 5]
class_include [1, 0] - [1, 24]
  path: word [1, 15] - [1, 23]
package_include [3, 0] - [3, 22]
  path: word [3, 12] - [3, 21]
begin [5, 0] - [5, 16]
  name: word [5, 7] - [5, 15]
text [7, 1] - [7, 4]
  word [7, 1] - [7, 4]
text [7, 8] - [7, 9]
  word [7, 8] - [7, 9]
generic_command_name [7, 10] - [7, 19]
text [7, 21] - [7, 22]
  word [7, 21] - [7, 22]
generic_command [7, 22] - [7, 28]
  name: generic_command_name [7, 22] - [7, 28]
text [7, 28] - [7, 31]
  word [7, 30] - [7, 31]
ERROR [7, 31] - [7, 35]
text [7, 36] - [7, 39]
  word [7, 36] - [7, 39]
text [7, 43] - [7, 44]
  word [7, 43] - [7, 44]
generic_command_name [7, 45] - [7, 54]
text [7, 56] - [7, 58]
  word [7, 56] - [7, 57]
generic_command [7, 59] - [7, 65]
  name: generic_command_name [7, 59] - [7, 65]
ERROR [7, 65] - [7, 69]
text [7, 69] - [7, 70]
  word [7, 69] - [7, 70]
generic_command [9, 0] - [9, 14]
  name: generic_command_name [9, 0] - [9, 4]
  arg: brace_group [9, 4] - [9, 14]
    child: text [9, 5] - [9, 13]
      word [9, 5] - [9, 13]
```

**Comment by pfoerster** [comment]
Thanks for the report.
Can you try 7f720661de5316c0f8fee956526d4002fa1086d8, please? I lifted the restrictions when parsing commands a bit.

**Comment by cionx** [comment]
Thanks, with 7f720661de5316c0f8fee956526d4002fa1086d8 thinks looks correct again. (The syntax highlight is correct, and the syntex tree generated by `tree-sitter parse` also looks better.)
