### ISSUE TITLE
Syntax highlighting doesn't highlight properly

### ISSUE THREAD

**Issue by inthepanchine** [latex-lsp/tree-sitter-latex#23]
I just installed the TreeSitter Latex grammar in NeoVim, but it doesn't seem to work or highlight properly.

Here two images of the issue.

<img width="696" alt="Screenshot 2022-01-25 at 21 55 58" src="https://user-images.githubusercontent.com/42863651/151058285-02396116-ee63-4c89-93c8-30e37dbcceda.png">
<img width="696" alt="Screenshot 2022-01-25 at 21 57 26" src="https://user-images.githubusercontent.com/42863651/151058492-3c60ad77-0942-45d2-a391-3ec06f5de1d4.png">

If someone can tell me if it's a bug or just my configuration mistake.

**Comment by clason** [comment]
Looks about right. Make sure your colorscheme actually assigns the needed highlight groups.

If you think there is an issue with tree-sitter highlighting in Neovim, please open an [issue there](https://github.com/nvim-treesitter/nvim-treesitter/issues/new?assignees=&labels=highlights&template=highlighting_issue.yml).

**Comment by pfoerster** [comment]
I agree with @clason. This looks like an highlighting/color scheme issue. Have you tried another color scheme? The examples you listed do not look particularly complicated so I do not think it is a parsing issue.
The highlighting queries don't live in this repository. Instead, they are a part of the `nvim-treesitter` repository.

**Comment by inthepanchine** [comment]
There actually was an error. By running `:checkhealth` I found out that there had been some kind of error while installing. Just  did a `:TSUpdate latex` and that worked out.

My bad I didn't do it before.
