### ISSUE TITLE
`\newtheorem` environment error

### ISSUE THREAD

**Issue by mathjiajia** [latex-lsp/tree-sitter-latex#24]
Look at the pic below.
This numbered environment command `\newtheorem{definition}{Definition}[section]`
was recognised as an error.
The unnumbered environments are not affected, such as `\newtheorem*{remark}{Remark}`.

<img width="1271" alt="Screenshot 2022-02-04 at 1 14 12 PM" src="https://user-images.githubusercontent.com/35106942/152475909-a1f7b712-6af3-4578-8ed9-1623c168eb15.png">

**Comment by pfoerster** [comment]
Thanks for the report. There was missing `optional` in the `theorem_definition` rule. The example you provided can now be parsed without errors 👍 .

**Comment by mathjiajia** [comment]
Thanks. It has been fixed now.
