### ISSUE TITLE
\usetikzlibrary should have same highlighting as \usepackage for multiple libraries

### ISSUE THREAD

**Issue by tarsobcaldas** [latex-lsp/tree-sitter-latex#28]
The command \usetikzlibrary only highlights the first item on a list, but the expected behavior should be to color the same way as RequirePackage or usepackage

![tsusetikzlibrary](https://user-images.githubusercontent.com/40038251/154687221-b139e36a-e6be-41cd-94ce-477180730d43.png)

**Comment by clason** [comment]
Should be enough to replace `curly_group_text` with `curly_group_text_list` in https://github.com/latex-lsp/tree-sitter-latex/blob/cd75e362a17c22ed90bcbdbaa78c2c7519ceb094/grammar.js#L996, right?

**Comment by tarsobcaldas** [comment]
It is now working as intended :)
