### ISSUE TITLE
\color recognizes as error when the argument is a command

### ISSUE THREAD

**Issue by tarsobcaldas** [latex-lsp/tree-sitter-latex#29]
Like in latex-lsp/texlab#557, \color and similar commands, like pagecolor, throws an error when the chosen color is a command. It is now fixed on TeXLab, and could be updated here as well.

**Comment by pfoerster** [comment]
Sorry for the late response. This has been fixed by 1ea9f87d30df20e13cde292ff4d6c4d8dd979b16.
