### ISSUE TITLE
`\chapter` highlight breaks when using optional argument

### ISSUE THREAD

**Issue by tarsobcaldas** [latex-lsp/tree-sitter-latex#39]
When using the command `\chapter` with an optional argument, the coloring doesn't work, like in the picture below. This also happens with `\section` and similar commands.

![image](https://user-images.githubusercontent.com/40038251/163045235-070ba5a9-828e-4b6d-b50d-649c0d020aa6.png)

**Comment by clason** [comment]
This seems to be parsed correctly, e.g.
```
chapter [3, 0] - [905, 13]
  command: "\chapter" [3, 0] - [3, 8]
  "[" [3, 8] - [3, 9]
  "]" [3, 9] - [3, 10]
  curly_group [3, 10] - [3, 51]
    "{" [3, 10] - [3, 11]
    text [3, 11] - [3, 50]
      word: word [3, 11] - [3, 25]
      word: word [3, 26] - [3, 36]
      word: word [3, 37] - [3, 40]
      word: word [3, 41] - [3, 50]
    "}" [3, 50] - [3, 51]
```
but it breaks the query. In any case, adding a `field('short', optional($.brack_group_argc))` or somesuch to the sectioning commands seems to me the right thing to do.

**Comment by pfoerster** [comment]
> In any case, adding a field('short', optional($.brack_group_argc)) or somesuch to the sectioning commands seems to me the right thing to do.

Definitely. I have added the extra field for the ToC entry name in a6926f5263cb1be193f230123139fbc34a04679c.

**Comment by clason** [comment]
Added in Neovim: https://github.com/nvim-treesitter/nvim-treesitter/pull/2783
