### ISSUE TITLE
`\newenvironment` hightlight not working

### ISSUE THREAD

**Issue by tarsobcaldas** [latex-lsp/tree-sitter-latex#40]
Although `\renewenvironment` is properly highlighted, `\newenvironment` is not

![image](https://user-images.githubusercontent.com/40038251/163203508-7f18e2b1-e061-4c0f-b011-55bf23628a9d.png)

**Comment by clason** [comment]
What editor are you using?

(The reason is that `\newenvironment` -- which takes _three_ mandatory arguments, by the way -- is a separate node, while `\renewenvironment` is a generic command. These should be treated the same, in any case.)

**Comment by pfoerster** [comment]
The grammar now treats `\renewenvironment` and `\newenvironment` the same way (e4112094b3dbaae246236b586073729d98699043).

**Comment by clason** [comment]
Should be working now: https://github.com/nvim-treesitter/nvim-treesitter/pull/2783
