### ISSUE TITLE
Language injection: R

### ISSUE THREAD

**Issue by bamonroe** [latex-lsp/tree-sitter-latex#41]
I was hoping that you could implement a grammar rule to recognize nodes injecting R code. Rnoweb documents are just Latex documents with additional markup containing R code that is then parsed by the [knitr](https://yihui.org/knitr/) R package and injected into the document. In particular, there is an inline command to inject R code used like `One plus one is equal to \Sexp{1 + 1}`, and there is a block that takes the form:

```
<< [some options here] >>==
[R code goes here]
@
```
The opening `<<` and closing `@` must both be the first characters on the line.

I use nvim-treesitter, and I understand from the conversation in issue #18 that the injection queries will need to written in that project, not here, but it would be useful to have a node type like `rcode_environment` to make the queries easier to write. Thanks very much for all your work on this project.

**Comment by clason** [comment]
For what it's worth, I disagree: R injection is not part of the LaTeX language, so this should not be part of a  LaTeX parser.

Rather this should be done the other way around: create an `Rnoweb` parser (which is the proper filetype anyway) that allows for LaTeX injections.

**Comment by bamonroe** [comment]
Thanks @clason, I think you might be right. I gave it a shot here: [bamonroe/tree-sitter-rnoweb](https://github.com/bamonroe/tree-sitter-rnoweb). If you have the time and inclination, I'd appreciate you giving it a look-over. I define a 'latex' node, and a 'renv' node, neither of which are very detailed, they only serve as top-level nodes for language injection later. 

One issue I'm having is that an `renv` breaks apart other latex environments, in particular, it'll basically always break `\begin{document}`. I think I need to use the `is_at_included_range_start` function of an external scanner to link the top-level latex nodes, but it isn't clear to me how. Any ideas?
