### ISSUE TITLE
incorrect capture of `\emph{foo}`

### ISSUE THREAD

**Issue by mathjiajia** [latex-lsp/tree-sitter-latex#42]
See the two screenshots below:
If there is a `\emph` curly_group, followed by a bracket, it will capture them together as a generic command.

<img width="492" alt="Screenshot 2022-04-16 at 6 09 00 PM" src="https://user-images.githubusercontent.com/35106942/163670981-759079af-8964-4658-a991-00341e74e223.png">
<img width="550" alt="Screenshot 2022-04-16 at 6 09 10 PM" src="https://user-images.githubusercontent.com/35106942/163670982-8fe9848c-713d-408a-bb51-45bc0bfd3f4a.png">

**Comment by du-da** [comment]
At a first glance, this particular example might be solved by setting a fixed order within the `generic_command` rule. This is based on the assumption that a curly bracket must not be followed by another argument type (round paren or bracket) (?)
```
seq(
	field('command', $.command_name),
	repeat(field('arg', $.mixed_group)),
	repeat(field('arg', $.curly_group))
))
```

However, the general issue of the `generic_command` "absorbing" any subsequent groups remains.

example:
```
\LaTeX(whatever)
\emph{test}{whatever}
```

parse tree:
```
(source_file [0, 0] - [2, 0]
  (generic_command [0, 0] - [0, 16]
    command: (command_name [0, 0] - [0, 6])
    arg: (mixed_group [0, 6] - [0, 16]
      (text [0, 7] - [0, 15]
        word: (word [0, 7] - [0, 15]))))
  (generic_command [1, 0] - [1, 21]
    command: (command_name [1, 0] - [1, 5])
    arg: (curly_group [1, 5] - [1, 11]
      (text [1, 6] - [1, 10]
        word: (word [1, 6] - [1, 10])))
    arg: (curly_group [1, 11] - [1, 21]
      (text [1, 12] - [1, 20]
        word: (word [1, 12] - [1, 20])))))
```

**Comment by pfoerster** [comment]
Thanks for the report. Unfortunately, this a quite difficult problem to solve without semantic information.

> This is based on the assumption that a curly-brace-argument must not be followed by another argument type (round paren or bracket) (?)

I am afraid that this assumption does not hold in the general case. Consider the `\newtheorem` command:
```
\newtheorem{<name>}{<heading>}[<counter>]
```
While this specific case is handled by a special rule in the grammar, I think there are other instances too. In the general case, you need to know the number of arguments of the command so I am not sure on how to solve this problem from a `tree-sitter` grammar.

**Comment by clason** [comment]
One possible thing is to not allow spaces between the tokens -- even if that would be allowed in LaTeX.

Right now you're stuck between a rock and a hard place: either way, something gets parsed wrong. And I would argue that it's better to _not_ parse something that's written in a legal but unusual way (in particular, when it's easy to modify the code so it parses correctly) than _incorrectly_ parse something that is harder to rewrite?

**Comment by pfoerster** [comment]
> One possible thing is to not allow spaces between the tokens -- even if that would be allowed in LaTeX.

Yeah, this sounds like a good idea. I'll try to work something out. Immediate tokens should be helpful here.

**Comment by pfoerster** [comment]
> I'll try to work something out. Immediate tokens should be helpful here.

Hmm. It turns out that this is much more work than I thought. Immediate tokens and the external scanner do not seem to help here without huge modifications. One could remove the `extras` and inline them where appropriate but I hope that there is a better solution available.

**Comment by clason** [comment]
I see. Would a partial solution be to at least ignore parens `(`, as I think `\foo{bar}(baz)` is not a valid command syntax in LaTeX?

Alternatively, is this something that could/should be handled on the level of queries? (I'm not an expert, but literal matching and ignoring is possible in principle.)

**Comment by pfoerster** [comment]
> I see. Would a partial solution be to at least ignore parens (, as I think \foo{bar}(baz) is not a valid command syntax in LaTeX?

I think you can define a command this way. I remember seeing it once but it is probably not worth it to keep the rule (see 8c5d90e78fa58ee6acab465ffa9a53e8b7b2c69c).
