### ISSUE TITLE
`\{` in math mode acting as error

### ISSUE THREAD

**Issue by tarsobcaldas** [latex-lsp/tree-sitter-latex#43]
Sometimes in display math I use `\left\{ ... \right.` is being treated as an error and incorrectly displaying all text red (this also happens without `\left` and `\right`):
![image](https://user-images.githubusercontent.com/40038251/167270943-84758882-a330-425e-bf6a-9b8507c4e972.png)

Outside math mode, `\{` does not result in error:
![image](https://user-images.githubusercontent.com/40038251/167270959-320f1dad-8e51-4c0f-b72f-2f7598049121.png)

Also, `\left` without `\right` (and vice-versa) is an error in LaTeX, maybe this could be treated as an error (at the moment it doesn't).

I'm using Neovim

**Comment by pfoerster** [comment]
> Sometimes in display math I use \left\{ ... \right. is being treated as an error and incorrectly displaying all text red (this also happens without \left and \right):

Thanks for the report. The error occurs because it tries to complete the `math_set` rule (see https://github.com/latex-lsp/tree-sitter-latex/pull/9) and there is no matching brace. Adding a new rule that parses `\left` and `\right` correctly should fix both problems (see 692215e).

**Comment by tarsobcaldas** [comment]
It solved the problem when using `\left{ \right.`, but created another problem:

It's highlighting `\left \right` differently with either brackets, parenthis or braces
![image](https://user-images.githubusercontent.com/40038251/167918428-e27465e2-d26e-4066-a762-5d0169de68eb.png)
![image](https://user-images.githubusercontent.com/40038251/167918482-1d340ff6-4713-41a8-82ac-1c6f47fea397.png)

And with `\left( \right.` it highlights the left parenthesis in red.
![image](https://user-images.githubusercontent.com/40038251/167918536-43580178-f51a-42d2-82ff-b8a79525cc16.png)

**Comment by clason** [comment]
Well, yes, `\left{` isn't valid TeX -- you probably mean `\left\{`?

**Comment by pfoerster** [comment]
> And with \left( \right. it highlights the left parenthesis in red.

This case should be fixed with 3b370b5ca3948312738b4f27b2a12e4bb58907a2.

**Comment by tarsobcaldas** [comment]
It is now working fine. Thanks!
