### ISSUE TITLE
[request] Cutting a release tag

### ISSUE THREAD

**Issue by Will-Sommers** [latex-lsp/tree-sitter-latex#46]
Hi y'all! 

Thanks for all of the work on this! I'm opening an issue to see if y'all would be up for cutting a release tag. We currently rely on a SHA but would love to rely on a version if possible!

Thank you!

**Comment by pfoerster** [comment]
> I'm opening an issue to see if y'all would be up for cutting a release tag

No problem :) https://github.com/latex-lsp/tree-sitter-latex/releases/tag/v0.1.0

**Comment by Will-Sommers** [comment]
Thanks!
