### ISSUE TITLE
Unmatching brackets breaks math mode

### ISSUE THREAD

**Issue by tarsobcaldas** [latex-lsp/tree-sitter-latex#48]
![image](https://user-images.githubusercontent.com/40038251/173621215-389176cc-bd82-4f2b-a9e2-69b2368d151e.png)

If you use brackets to represent open and closed sets, often you unmatching brackets, and it is currently breaking math mode delimiter's highlight.

**Comment by pfoerster** [comment]
Thanks for the report. I think there are two ways to fix this issue:

1. Do not capture the arguments of a command; instead they are siblings of the command node
2. Similar to above but only in math mode

The first solution is much simpler but it might break a lot of existing highlighting functions.
I've tried the second approach but I have not come up with a way such that `tree-sitter generate` uses the precedences correctly.

@clason What do you think?

**Comment by clason** [comment]
Oh boy... I think

1. this is a damned if you do, damned if you don't situation, and
2. this is why people usually use round parens for open intervals :]

(Seriously, I haven't seen "inside-out brackets" for twenty years.)

**Comment by pfoerster** [comment]
> I think there are two ways to fix this issue:

Actually, there's a third way: only match brackets for the commands baked into the grammar like `\usepackage`. Looking at `nvim-treesitter`, I do not think, this will break much (if anything).

**Comment by clason** [comment]
(Although there's a large number of packages in math mode -- and even custom commands -- that people use; I feel that this is a slippery slope and will leave to people requesting more and more commands to be added. And I personally prefer consistency.)

**Comment by pfoerster** [comment]
> I feel that this is a slippery slope and will leave to people requesting more and more commands to be added

Yeah, I agree. The number of commands baked into the grammar should be small. Every command blows up the grammar size by a lot (`parser.c` is a huge file).

> Actually, there's a third way: only match brackets for the commands baked into the grammar like \usepackage. Looking at nvim-treesitter, I do not think, this will break much (if anything).

I have a PR for this one: #51.
