### ISSUE TITLE
Inconsistency in highlighting `\section` and `\section*`

### ISSUE THREAD

**Issue by paniash** [latex-lsp/tree-sitter-latex#5]
I noticed that there is a slight inconsistency in highlighting numbered and non-numbered sections (and subsections) in a LaTeX document. The non-numbered section has no highlighting, in contrast to the numbered section.

**Screenshot**:
![pic-window-210629-1628-42](https://user-images.githubusercontent.com/59497618/123786287-27bab000-d8f7-11eb-8283-3d81c41d97b1.png)

**Comment by clason** [comment]
Fixed downstream: https://github.com/nvim-treesitter/nvim-treesitter/pull/1455 (this was not a problem with the parser but the queries).
