### ISSUE TITLE
Parsing ERROR for `minted` with options

### ISSUE THREAD

**Issue by vigoux** [latex-lsp/tree-sitter-latex#55]
Hi,

I have encountered a parsing error when using the `minted` environment with environment options.

Here is a minimal reproducting example:
```latex
\documentclass{article}

\begin{document}
  \begin{minted}[autogobble]{python}
    foo()
  \end{minted}
\end{document}
```

Note that removing the `[autogobble]` makes everything fine again.

**Comment by pfoerster** [comment]
Thanks for the report. This should be fixed now :)

**Comment by vigoux** [comment]
Awesome, thanks!

**Comment by gnull** [comment]
Will this work for custom minted-based environments like

```latex
\newminted[hs]{haskell}{}

\begin{hs}
main = putStrLn "hello"
\end{hs}
```

?
