### ISSUE TITLE
Broken highlight in neovim

### ISSUE THREAD

**Issue by tarsobcaldas** [latex-lsp/tree-sitter-latex#57]
Highlight that was previously working is not anymore. There are no changes for a great
number of themes in begin and end; chapter, section and similar commands; labels and references; also math mode.

![Screenshot from 2022-10-17 21-36-07](https://user-images.githubusercontent.com/40038251/196278364-7a85a860-53be-4dce-9024-340082ec8eea.png)![Screenshot from 2022-10-17 21-36-14](https://user-images.githubusercontent.com/40038251/196278366-90251655-5ac2-425e-9416-2144568b7887.png)![Screenshot from 2022-10-17 21-36-36](https://user-images.githubusercontent.com/40038251/196278369-c1f5cc9a-9284-409c-955d-3d27d28ec57f.png)
![Screenshot from 2022-10-17 21-36-41](https://user-images.githubusercontent.com/40038251/196278372-61cd95df-3f65-46c6-aeb5-9840cdfc71c4.png)![Screenshot from 2022-10-17 21-36-49](https://user-images.githubusercontent.com/40038251/196278376-f4b1df8a-cdda-4379-9621-a7e87d1d167e.png)![Screenshot from 2022-10-17 21-37-12](https://user-images.githubusercontent.com/40038251/196278377-edf8f961-95b1-43b2-8bbc-0718d5d09c14.png)

**Comment by clason** [comment]
This has nothing to do with the parser; nvim-treesitter has removed the legacy `TS*` highlight groups after Neovim 0.8 (with support for native treesitter groups) was released.

**Comment by tarsobcaldas** [comment]
Uninstalled and then reinstalled the parser and it started working again.

**Comment by tarsobcaldas** [comment]
Now I understand that is a problem of the colorschemes updating their interaction with treesitter, as one of these themes did it and solved most of the problems.
