### ISSUE TITLE
Content of `\big[ ... \big]` parsed as parameter

### ISSUE THREAD

**Issue by canonicalmonty** [latex-lsp/tree-sitter-latex#58]
I frequently use the commands `\big`, `\bigg`, `\Big`, `\Bigg` and the variations with -l and -r in math mode. With nvim-treesitter when I use these commands with brackets the content appears to be parsed as parameters as shown in the image. 
![1666650538](https://user-images.githubusercontent.com/59242684/197641584-0be95642-cd3a-4709-bbbb-3f2eeabea706.png)

I think the desired behavior would be like that of `\left...\right` --- maybe relevant: https://github.com/latex-lsp/tree-sitter-latex/issues/43.  In general, it seems that `\big, \bigg...` is not parsed the same as `\left...\right` in any of the cases shown. Is it intended behavior?

**Comment by pfoerster** [comment]
Thanks for the report. `\big`, `\bigl` and `\bigr` are now treated similar to `\left` and `\right` in `v0.2.1` :+1:

**Comment by canonicalmonty** [comment]
That was fast. Thank you!!

One question though, the same applies to `\bigg`, `\biggl`, `\biggr`, `\Big`, `\Bigr`, `\Bigl`, `\Bigg`, `\Biggr`, `\Biggl`?

**Comment by pfoerster** [comment]
> One question though, the same applies to \bigg, \biggl, \biggr, \Big, \Bigr, \Bigl, \Bigg, \Biggr, \Biggl?

Now it does :)
