### ISSUE TITLE
Incorrect capture of parentheses inside ```$...$```

### ISSUE THREAD

**Issue by adityadesaha** [latex-lsp/tree-sitter-latex#61]
If I have the text ```$((($``` the syntax tree is looking like
```
inline_formula [0, 0] - [0, 5]
```

It's not recognizing anything inside the ```inline_formula``` environnment. In this case, how would I query for the contents _inside_ the dollar signs?

**Comment by pfoerster** [comment]
Thanks for the question. The CLI does not output unnamed nodes like `(` or `$` but they are still part of the tree. You can take a look at the grammar in the `nvim-treesitter` repository as an example:

https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/latex/highlights.scm#L33
