### ISSUE TITLE
Failed to build wasm

### ISSUE THREAD

**Issue by Troublor** [latex-lsp/tree-sitter-latex#68]
I tried to build `tree-sitter-latex` using `tree-sitter build-wasm` command and got the following error:
```
> tree-sitter build-wasm node_modules/@pfoerster/tree-sitter-latex --docker 
emcc command failed - docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: mkdir /src/tree-sitter-latex: file exists: unknown.
```

However, if I built outside docker with `emscripten` installed in PATH, it succeeded. 
What could be the problem?

**Comment by pfoerster** [comment]
Sorry for the late response. Are you still having this issue? I am not able to reproduce this issue. Does it happen with other grammars (like `tree-sitter-javascript`), too?
