### ISSUE TITLE
Path should include dollar sign (as in $HOME)

### ISSUE THREAD

**Issue by vitorof** [latex-lsp/tree-sitter-latex#7]
If I use environment variables in paths, such as in `\addbibresource{$HOME/ref.bib}`, then it is parsed as an error, as if the dollar sign were an opening delimiter for math expressions, even though it compiles fine with any LaTeX engine.

**Comment by yhu266** [comment]
I encountered a similar issue with strings starting with `$`. The following code has wrong highlighting in the `rm -rf` line,

```latex
To clear \lstinline{biber} cache, run
\begin{lstlisting}[language=bash]
rm -rf "$(biber --cache)"
\end{lstlisting}
```

**Comment by clason** [comment]
The `rm -rf` line is not LaTeX and therefore not relevant to the highlighter (this should be handled on the tree-sitter level by injecting a bash parser).

**Comment by pfoerster** [comment]
Thanks for the report. https://github.com/latex-lsp/tree-sitter-latex/commit/fbbf4c4e90604dee1f9e349686b24f7248832121 should fix the issue with dollar and other characters inside paths. The highlighting queries over at nvim-treesitter will need a small update though.

**Comment by clason** [comment]
Nor sure, actually; should test first :) ( @theHamsta )

**Comment by theHamsta** [comment]
We have a CI jobs that updates the parsers regularly. When no nodes are renamed, removed, added no manual action is required from nvim-treesitter side.

I would recommend to add the example above to corpus.txt to test it. So just test it locally with `tree-sitter test` and if the parsed AST is correct create a PR to add the test case to this repo.

**Comment by clason** [comment]
Yeah, I don't think we use the `(word)` capture for the argument of `\input{}`, `\bibliography{}`, etc., so there shouldn't be a breakage.

**Comment by pfoerster** [comment]
Sorry for the long wait. There are now test cases for both examples. The source code listing is handled using an external scanner, which outputs a `(source_code)` node.
