### ISSUE TITLE
Add `$$ $$` and `$  $` highlight?

### ISSUE THREAD

**Issue by Y-S-A** [latex-lsp/tree-sitter-latex#72]
It seems that the $ for math mode aren't highlighted. And it would be great help(I think?) to highlight them.
![图片](https://user-images.githubusercontent.com/93212117/217714758-15569429-1cbf-49c5-928b-db4949d6d597.png)

**Comment by clason** [comment]
They are, your colorscheme just needs to set `@text.math`.

(And `$$` is not valid LaTeX but plain TeX and therefore not recommended.)

**Comment by pfoerster** [comment]
Note that this repository just provides the parser and not the actual highlighting queries.
The rules to parse math mode can be found here:

https://github.com/latex-lsp/tree-sitter-latex/blob/6b7ea839307670e6bda011f888717d3a882ecc09/grammar.js#L445-L453

**Comment by clason** [comment]
Yes, this is an nvim-treesitter issue (or, rather, a colorscheme issue, since we do have queries for those nodes).

**Comment by Myzel394** [comment]
I can't even get syntax highlighting to work inside the dollar signs at all :(. Is it currently broken or am I doing something wrong?
