### ISSUE TITLE
Treating xparse syntax the same as newcommand

### ISSUE THREAD

**Issue by tarsobcaldas** [latex-lsp/tree-sitter-latex#82]
The [`xparse`](https://ftp.eq.uc.pt/software/TeX/macros/latex/contrib/l3packages/xparse.pdf) package is part of the LaTeX 3 syntax as well, so I think it would nice if it had a highlighting similar to the command definitions in TeX and LaTeX

![image](https://user-images.githubusercontent.com/40038251/232238388-01548e4d-ef2c-4edb-b600-f129fedb7bb4.png)

**Comment by pfoerster** [comment]
@tarsobcaldas Thanks for the suggestion! I have added the missing commands in 91832daef56069407cd511f8a13fdc855a372c69.
