### ISSUE TITLE
Missing citation commands

### ISSUE THREAD

**Issue by vigoux** [latex-lsp/tree-sitter-latex#94]
Hi,

It appears that some citation command (especially APA-style ones) are not supported by this parser, here is a full list for reference:
- `\citeA[postfix]{keys}`
- `\citeR<prefix>[postfix]{keys}`
- `\citeS[postfix]{keys}`
- `\citeyearR[postfix]{keys}`

I can open a PR if needed.

**Comment by pfoerster** [comment]
> I can open a PR if needed.

@vigoux Sure, a PR is more than welcome :)
